### ISSUE TITLE
请问如何知道我是否提交成功，以及一天可以提交多次吗

### ISSUE THREAD

**Issue by Weizhi-Zhong** [vico-dataset/vico-dataset.github.io#2]
亲爱的比赛组办方你好，我想问一下，提交结果之后是否会有什么提示呢，我点了submit按钮后，它颜色变淡不能再点击了，但是没有任何提示。My Submissions栏中也无纪录

此外，每天只能提交一次吗，可否取消此限制呢，因为测试那些指标需要ground truth视频，但是ground truth视频并没有公开，我们难以在本地环境下测试结果

**Comment by dc3ea9f** [comment]
Hi, weizhi,

欢迎参加Conversational Head Generation Challenge。

很抱歉给您带来的提交结果的问题，现已fix初次submission不能提交的问题，当提交过后，正常情况下浏览器会弹出成功提交的提示框，并通过邮件告知用户，在My Submissions中也会产生记录。

由于评测时间及个人精力限制，现在是在UTC-0时间下每天只允许提交一次，之后会考虑增加提交次数；参赛者可以尝试在本地自行划分train / valid集进行测试、提交结果。

祝您在比赛中取得好成绩！

**Comment by dc3ea9f** [comment]
Hi，现在网站允许每队每天每个track提交三次结果，评测结果会在24h内返回给用户
